language: node_js

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run build

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: dist
    github_token: $GITHUB_TOKEN
    on:
      branch: master
