@startuml

entity Spaceship {
  Spaceship
  Position
  Audio
}

entity AliveSpaceship extends Spaceship {
  Motion
  MotionControls
  Gun
  GunControls
  Collision
  Display
}

entity DeadSpaceship extends Spaceship {
  DeathThroes
  Display
  Animation
}

entity Bullet {
  Bullet
  Position
  Collision
  Motion
  Display
}

entity Asteroid {
  Asteroid
  Position
  Audio
}

entity AliveAsteroid extends Asteroid {
  Display
  Collision
  Motion
}

entity DeadAsteroid extends Asteroid {
  DeathThroes
  Display
  Animation
}

entity Game {
  GameState
  Hud
  Display
  Position
}

entity Wait {
  WaitForStart
  Display
  Position
}

@enduml
